### ISSUE TITLE
problem with file 3esl.txt

### ISSUE THREAD

**Issue by jacekbrek** [tomaszczerwonka/popular-words#2]
Hello,

I would like to get more information about this project. How am I supposed to find 1000 most popular words if in 3esl.txt file all words are unique. Did I misunderstand the task or is there a mistake in the data?

Regards,
Jacek

**Comment by tomaszczerwonka** [comment]
> Hello,
> 
> I would like to get more information about this project. How am I supposed to find 1000 most popular words if in 3esl.txt file all words are unique. Did I misunderstand the task or is there a mistake in the data?
> 
> Regards,
> Jacek

**Comment by tomaszczerwonka** [comment]
The file is OK. Please think what words file contains... what data. It contains dirty data and you have do something with them. What you will do with words for example like self-absorbed, self-appointed, self-assurance? Is this only single words for you. Another example are words 'Arctic' and 'arctic'. Is this the same word for you or not?
